### ISSUE TITLE
Submitting Favorites to API kicksback user password

### ISSUE THREAD

**Issue by stephencarrera** [rithmschool/hack-or-snooze-api#1]
<img width="117" alt="screenshot 2017-11-14 21 51 22" src="https://user-images.githubusercontent.com/27288950/32821028-334fe8f6-c986-11e7-8b59-5d91ca32f3ff.png">

After a successful submission of adding a favorite to the server, the response includes the user's password.

**Comment by stephencarrera** [comment]
![gif of the workflow](https://user-images.githubusercontent.com/27288950/32821475-6bbbb24a-c988-11e7-854b-9cc7a530314a.gif)

**Comment by hueter** [comment]
Thanks for the report; this has been fixed in the latest version (1.1.0)
